import Link from "next/link";
import SiteHeader from "../components/SiteHeader";
import ProductFeed from "../components/ProductFeed";
import RecentlyViewed from "../components/RecentlyViewed";
const categories=["홈","전체","디지털","가전","생활","주방","패션","뷰티"];
const categoryIcons:Record<string,React.ReactNode>={홈:<svg viewBox="0 0 24 24"><path d="m3.5 10.5 8.5-7 8.5 7M5.5 9.5V21h13V9.5M9.5 21v-6h5v6"/></svg>,전체:<svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>,디지털:<svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="12" rx="2"/><path d="M8 21h8M12 17v4"/></svg>,가전:<svg viewBox="0 0 24 24"><rect x="5" y="3" width="14" height="18" rx="2"/><circle cx="12" cy="13" r="4"/><path d="M8 7h1M12 7h4"/></svg>,생활:<svg viewBox="0 0 24 24"><path d="M7 10h10l1 11H6l1-11ZM9 10V7a3 3 0 0 1 6 0v3"/></svg>,주방:<svg viewBox="0 0 24 24"><path d="M7 3v7M4 3v5a3 3 0 0 0 6 0V3M7 10v11M16 3v18M16 3c3 2 4 5 4 8h-4"/></svg>,패션:<svg viewBox="0 0 24 24"><path d="m8 4 4 3 4-3 5 5-3 3v9H6v-9L3 9l5-5Z"/></svg>,뷰티:<svg viewBox="0 0 24 24"><path d="M9 3h6v5l2 3v10H7V11l2-3V3ZM9 8h6"/></svg>};

const slides=[
["today","1 / 6","오늘 뭐 살지|고민된다면?","당신의 일상을 더 좋게, 오늘의 추천 상품","/search?q=오늘의추천"],
["best","2 / 6","지금, 가장 인기있는|BEST 100","사람들이 많이 보는 상품만 모았어요","/#best"],
["under","3 / 6","5천원으로도|좋은 게 많아요","작지만 확실한 행복, 5천원 이하 상품","/search?q=5000원이하"],
["single","4 / 6","1인가구를 위한|스마트한 선택","작은 공간도 더 특별하게","/search?q=1인가구"],
["newly","5 / 6","신혼·이사 준비도|9호와 함께","새로운 시작을 더 설레게","/search?q=신혼가전"],
["digital","6 / 6","디지털·PC로|더 넓은 가능성","일도, 취미도, 더 즐겁게","/search?q=디지털"]
];
export default function Home(){return <main className="athlerHome"><SiteHeader/><section className="heroViewport" aria-label="추천 기획전"><div className="heroRail">{slides.map((s,i)=><article className={`heroSlide hero-${s[0]}`} key={s[0]}><div className="heroShade"/><div className="heroContent"><span>{s[1]}</span><h1>{s[2].split("|").map(x=><span className="heroLine" key={x}>{x}</span>)}</h1><p>{s[3]}</p><Link href={s[4]}>지금 구경하기 <b>›</b></Link></div><div className="heroDots">{slides.map((_,j)=><i className={j===i?"on":""} key={j}/>)}</div></article>)}</div></section><nav className="categoryIcons" id="categories">{categories.map((x,i)=><Link className={i===0?"active":""} key={x} href={x==="홈"?"/":x==="전체"?"/#best":`/search?q=${encodeURIComponent(x)}`}><span>{categoryIcons[x]}</span><b>{x}</b></Link>)}</nav><div id="recent"><RecentlyViewed/></div><section className="feedSection" id="best"><div className="feedTitle"><div><h2>지금 많이 보는 상품</h2></div><Link href="/search?q=인기상품">더보기 ›</Link></div><ProductFeed limit={6} variant="list"/></section><section className="feedSection feedSection--soft"><div className="feedTitle"><div><h2>가볍게 둘러보는 추천</h2></div><Link href="/search?q=추천">더보기 ›</Link></div><ProductFeed limit={8} variant="rail"/></section><section className="feedSection"><div className="feedTitle"><div><h2>가격대별 인기상품</h2></div><Link href="/search?q=인기상품">더보기 ›</Link></div><ProductFeed limit={6} variant="grid"/></section><footer className="mobileFooter"><strong>9HO</strong><p>상품을 직접 판매하지 않는 가격비교·추천 서비스입니다.<br/>상품 정보와 가격은 판매처에 따라 변경될 수 있습니다.</p><nav><Link href="/about">서비스 안내</Link><Link href="/terms">이용약관</Link><Link href="/privacy">개인정보처리방침</Link></nav><small>일부 링크를 통한 구매 시 9HO가 제휴 수수료를 받을 수 있습니다.</small><em>© 2026 9HO</em></footer></main>}
