export type LongtailKeyword={
 slug:string;label:string;group:"price"|"space"|"gift"|"digital"|"travel"|"pet"|"living"|"season";
 query:string;intro:string;
};
const rows:[string,string,LongtailKeyword["group"]][]=[
["quiet-vacuum-small-room","소음 적은 원룸용 청소기","space"],["gift-for-parents-under-50000","5만원 이하 부모님 선물","gift"],["monitor-for-small-desk","책상 좁아도 쓰기 좋은 모니터","digital"],["compact-dishwasher-no-install","설치 필요 없는 소형 식기세척기","space"],["off-grid-car-camping-items","차박할 때 전기 없이 쓰는 용품","travel"],["vacuum-for-dog-hair","반려견 털 청소하기 좋은 청소기","pet"],["carry-on-travel-items","기내 반입 가능한 여행용품","travel"],["value-tablet-100k","10만원대 가성비 태블릿","digital"],
["housewarming-gift-under-30000","3만원 이하 집들이 선물","gift"],["practical-gift-under-10000","1만원 이하 실용적인 선물","price"],["appliances-for-small-studio","좁은 원룸에 놓기 좋은 가전","space"],["storage-for-small-home","수납공간 적은 집 정리용품","space"],["compact-home-office-items","재택근무 책상 공간 줄이는 제품","digital"],["portable-monitor-for-laptop","노트북과 같이 쓰기 좋은 휴대용 모니터","digital"],["long-battery-wireless-earbuds","충전 오래가는 무선 이어폰","digital"],["light-powerbank-for-commute","출퇴근용 가벼운 보조배터리","digital"],
["car-items-for-long-drive","장거리 운전에 편한 차량용품","travel"],["camping-gear-for-beginners","캠핑 초보가 먼저 사는 용품","travel"],["travel-packing-organizers","여행가방 부피 줄이는 정리용품","travel"],["neck-pillow-for-flight","비행기에서 쓰기 좋은 목베개","travel"],["cleaning-for-cat-hair","고양이 털 청소하기 좋은 제품","pet"],["pet-odor-home-items","반려동물 냄새 줄이는 생활용품","pet"],["kitchen-items-less-dishes","설거지 줄여주는 주방용품","living"],["microwave-cooking-tools","전자레인지로 간단히 쓰는 조리도구","living"],
["compact-bathroom-storage","욕실 공간 적게 차지하는 수납용품","space"],["desk-cable-organizers","전선 정리하기 좋은 데스크용품","living"],["energy-saving-summer-cooling","여름 전기료 부담 적은 냉방용품","season"],["heating-for-small-studio","겨울 원룸에서 쓰기 좋은 난방용품","season"],["rainy-season-laundry-drying","장마철 빨래 말리기 좋은 제품","season"],["fine-dust-home-appliances","미세먼지 많은 날 필요한 생활가전","season"],
["humid-summer-dehumidify","습한 여름 집안 뽀송하게 만드는 제품","season"],["cold-wave-warm-items","한파 때 체온 지키기 좋은 방한용품","season"],["spring-allergy-cleaning","봄철 꽃가루·먼지 청소에 좋은 제품","season"],["autumn-dry-home-items","건조한 가을에 쓰기 좋은 생활용품","season"],["hot-night-sleep-items","열대야에 잠들기 편한 수면용품","season"],["rainy-day-shoe-care","비 오는 날 신발 관리하기 좋은 제품","season"],
["gift-for-lover-under-50000","5만원 이하 연인 선물","gift"],["gift-for-friend-under-30000","3만원 이하 친구 선물","gift"],["birthday-practical-gift","생일에 주기 좋은 실용적인 선물","gift"],["housewarming-kitchen-gift","집들이에 좋은 주방용품 선물","gift"],["gift-for-coworker","직장 동료에게 부담 없이 주는 선물","gift"],["gift-for-newlyweds","신혼부부에게 주기 좋은 선물","gift"],["gift-for-grandparents","부모님·조부모님께 드리기 좋은 생활용품","gift"],
["under-20000-useful-items","2만원 이하 실용적인 생활용품","price"],["under-30000-value-items","3만원 이하 가성비 좋은 상품","price"],["under-50000-popular-items","5만원 이하 인기 상품","price"],["small-gift-under-5000","5천원 이하 소소한 선물","price"],["office-gift-under-10000","1만원 이하 직장 답례품","price"],["home-items-under-20000","2만원 이하 집에서 유용한 제품","price"],
["bedside-items-small-room","좁은 침실에서 쓰기 좋은 생활용품","space"],["tiny-kitchen-storage","좁은 주방 공간 살리는 수납용품","space"],["no-drill-storage-items","못 없이 설치하는 수납용품","space"],["foldable-small-home-items","필요할 때만 펴 쓰는 접이식 생활용품","space"],["studio-laundry-items","원룸 빨래 공간 줄이는 제품","space"],["small-entryway-storage","좁은 현관 정리에 좋은 제품","space"],
["laptop-accessories-work","노트북 작업 효율 높이는 액세서리","digital"],["tablet-study-accessories","태블릿 공부할 때 유용한 액세서리","digital"],["video-meeting-homeoffice","화상회의할 때 유용한 재택근무 용품","digital"],["desk-light-work","오래 작업할 때 편한 데스크 조명","digital"],["compact-keyboard-mouse","책상 공간 아끼는 키보드·마우스","digital"],["phone-accessories-commute","출퇴근할 때 유용한 스마트폰 액세서리","digital"],
["picnic-compact-items","가볍게 챙기는 피크닉 용품","travel"],["hiking-beginner-items","등산 초보가 챙기기 좋은 용품","travel"],["beach-travel-items","바다 여행 갈 때 챙기기 좋은 용품","travel"],["hotel-travel-items","호텔·숙소에서 유용한 여행용품","travel"],["family-trip-car-items","가족 여행 때 편한 차량용품","travel"],["weekend-camping-compact","주말 캠핑에 가볍게 챙기는 용품","travel"],
["pet-walk-items","반려견 산책할 때 유용한 용품","pet"],["pet-water-feeding","반려동물 급수·급식 편하게 하는 제품","pet"],["cat-home-play-items","실내 고양이 놀이에 좋은 용품","pet"],["pet-car-travel","반려동물과 차로 이동할 때 필요한 용품","pet"],["pet-home-storage","반려동물 용품 정리하기 좋은 제품","pet"],["pet-summer-cooling","여름철 반려동물 더위 줄이는 용품","pet"],["pet-winter-warm","겨울철 반려동물 보온에 좋은 용품","pet"],
["easy-bathroom-cleaning","욕실 청소 쉽게 하는 생활용품","living"],["food-storage-kitchen","식재료 보관 편하게 하는 주방용품","living"],["laundry-organizing-items","세탁·빨래 정리 편하게 하는 제품","living"],["bedroom-sleep-items","침실을 편안하게 만드는 수면용품","living"],["home-odor-control","집안 냄새 관리하기 좋은 생활용품","living"],["quick-cleaning-items","매일 간단히 청소하기 좋은 제품","living"],["kitchen-space-saving","주방 공간 아껴주는 생활용품","living"],["bathroom-dry-items","욕실 물기 관리하기 좋은 제품","living"]];
export const longtailKeywords:LongtailKeyword[]=rows.map(([slug,label,group])=>({slug,label,group,query:label,intro:`${label}을 찾을 때 가격만 보지 않고 크기·사용환경·편의성을 함께 살펴보세요. 9HO에서 관련 상품과 판매처 가격을 비교해 선택 조건을 좁혀볼 수 있습니다.`}));
export const getLongtail=(slug:string)=>longtailKeywords.find(x=>x.slug===slug);
